### ISSUE TITLE
Display readable size in SizeAndBranch column

### ISSUE THREAD

**Issue by Ordisoftware** [Darthholi/WDX_GitCommander#5]
@Darthholi Thank you. I use this awesome plugin to display the current branch and know where I am. In addition to x64 version, it would be nice to have the size of files displayed as selected in TCMD/Settings/TabStops for SizeAndBranch. Another thing is that pressing space on folder don't display size. I solve this like that:

![totalcmdgit1](https://user-images.githubusercontent.com/22332878/38370485-7b4ab1a8-38ea-11e8-99d7-d89dd0bc3f82.jpg)

![totalcmdgit2](https://user-images.githubusercontent.com/22332878/38370452-6a81512e-38ea-11e8-9fc6-91084ae39806.jpg)

**Comment by Ordisoftware** [comment]
@Darthholi I finally solve the problem of the size like that :fire: 

![totalcmdgit2](https://user-images.githubusercontent.com/22332878/38368457-a22b6164-38e5-11e8-84ce-1c4da03786fc.jpg)

**Comment by tbeu** [comment]
Using [v2.0.0](https://github.com/tbeu/WDX_GitCommander/releases/tag/v2.0.0) my recommended workaround is to not use `[=gitcmd.SizeAndBranch]`, but `[=gitcmd.DirBranch] [=tc.size.bkM2]` (or different unit for `tc.size`).

**Comment by Ordisoftware** [comment]
Yes, it is what I actually use (not explicitly mentioned when I wrote "*solved*" but only put the second image):

![image](https://user-images.githubusercontent.com/22332878/106373677-4c2c5380-637c-11eb-857a-fb39a96da8d6.png)

Thank you for the x64 version, now I can use TCMD64!
